#!/bin/bash 

# capture any input, set up test variable
server=$1
svrtest=":$server:"

# check for input to disconnect, else set default server
if [ $svrtest == ":disconnect:" ]; then
   /usr/bin/expressvpn disconnect
elif [ $svrtest == ":list:" ]; then
   /usr/bin/expressvpn list
elif [ $svrtest == "::" ]; then
   server=usda2
   echo "*** Starting EXPRESSVPN with connection to: $server"
   /usr/bin/expressvpn connect $server
   /usr/bin/xterm -T "ATTACHED"		\
		-bg Black 		\
		-fg Yellow		\
		-geometry 30x4		\
		-e watch 		\
		-g /usr/bin/expressvpn status &
else
   echo "*** Starting EXPRESSVPN with connection to: $server"
   /usr/bin/expressvpn connect $server
   /usr/bin/xterm -T "ATTACHED"		\
		-bg Black 		\
		-fg Yellow		\
		-geometry 30x4		\
		-e watch 		\
		-g /usr/bin/expressvpn status &
fi
