#!/bin/bash 

# capture any input, set up test variable
server=$1
svrtest=":$server:"

# generalize executable locations
EXPRESSVPN=$(which expressvpn)
XTERM=$(which xterm)

# check for input to disconnect, else set default server
if [ $svrtest == ":disconnect:" ]; then
   $EXPRESSVPN disconnect
elif [ $svrtest == ":list:" ]; then
   $EXPRESSVPN list
elif [ $svrtest == "::" ]; then
   server=usda2
   echo "*** Starting EXPRESSVPN with connection to: $server"
   $EXPRESSVPN connect $server
   $XTERM -T "ATTACHED"		\
		-bg Black 		\
		-fg Yellow		\
		-geometry 30x4		\
		-e watch 		\
		-g $EXPRESSVPN status &
else
   echo "*** Starting EXPRESSVPN with connection to: $server"
   $EXPRESSVPN connect $server
   $XTERM -T "ATTACHED"		\
		-bg Black 		\
		-fg Yellow		\
		-geometry 30x4		\
		-e watch 		\
		-g $EXPRESSVPN status &
fi
